# Generated by Django 4.2.1 on 2023-05-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('memo', models.TextField()),
                ('priority', models.CharField(choices=[('danger', 'high'), ('info', 'normal'), ('success', 'low')], max_length=50)),
                ('duedate', models.DateField()),
            ],
        ),
    ]
